import Vue from 'vue'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faBars,
    faCheck,
    faEdit,
    faEllipsisV,
    faExternalLinkAlt,
    faFileCsv,
    faFilter,
    faHome,
    faInfoCircle,
    faLevelUpAlt,
    faMoon,
    faPlus,
    faQuestionCircle,
    faSignOutAlt,
    faSort,
    faSun,
    faTable,
    faTimes,
    faTools,
    faTrashAlt,
    faUser,
} from '@fortawesome/free-solid-svg-icons'

library.add(
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faAngleUp,
    faBars,
    faCheck,
    faEdit,
    faEllipsisV,
    faExternalLinkAlt,
    faFileCsv,
    faFilter,
    faHome,
    faInfoCircle,
    faLevelUpAlt,
    faMoon,
    faPlus,
    faQuestionCircle,
    faSignOutAlt,
    faSort,
    faSun,
    faTable,
    faTimes,
    faTools,
    faTrashAlt,
    faUser,
)
Vue.component('font-awesome-icon', FontAwesomeIcon)
