name: "Playwright tests"

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    playwright:
        name: "Playwright Tests"
        runs-on: ubuntu-22.04
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v4"
            - name: "Setup Python"
              uses: "actions/setup-python@v4"
              with:
                  python-version: 3.12
            - name: "Setup Node"
              uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: "Install all dependencies"
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/requirements.txt
                  pip install -r requirements/test-requirements.txt
                  cd admin_ui && npm install
            - name: Build front end assets
              run: cd admin_ui && npm run build-only
            - name: Ensure Chromium is installed
              run: python -m playwright install chromium --with-deps
            - name: Start Playwright tests
              run: ./scripts/run-e2e-test.sh
            - uses: actions/upload-artifact@v4
              with:
                  name: playwright-artifacts
                  path: videos/
              if: always()
