name: "Playwright tests"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.11
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install all dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test-requirements.txt
          cd admin_ui && npm install
      - name: Build front end assets
        run: cd admin_ui && npm run build
      - name: Ensure Chromium is installed
        run: python -m playwright install chromium --with-deps
      - name: Start Playwright tests
        run: ./scripts/run-e2e-test.sh
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: videos/
        if: always()
        
