name: Release

on:
    release:
        types:
            - created

jobs:
    release:
        name: "Publish release"
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@v2"
            - uses: "actions/setup-python@v2"
              with:
                  python-version: 3.7
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: "Install dependencies"
              run: |
                pip install -r requirements/dev-requirements.txt
                pip install -r requirements/requirements.txt
            - name: "Publish to PyPI"
              run: "./scripts/release.sh"
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
